# Use an official Python runtime as the base image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=tracker.settings.production

# Set the working directory in the container
WORKDIR /app

# Copy the project app into the container
COPY . /app/

# Install project dependencies
RUN pip install --upgrade pip 
RUN pip install -r requirements.txt
